name: Deploy to Firebase Hosting on merge
'on':
  push:
    branches:
      - main
jobs:
  build_and_deploy_prod:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v3.3.0
      - name: Lint
        run: npm run lint
      - name: Install
        run: npm install
      - name: Build Prod
        run: npm run build
        env:
          BACKEND_URL: ${{ secrets.BACKEND_URL }}
      - uses: FirebaseExtended/action-hosting-deploy@v0
        with:
          repoToken: '${{ secrets.GITHUB_TOKEN }}'
          firebaseServiceAccount: '${{ secrets.FIREBASE_SERVICE_ACCOUNT_PASSIVE_FUNDS }}'
          channelId: live
          projectId: passive-funds
